# Generated by Django 3.1.7 on 2021-04-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='char2_scndinterro',
            new_name='char2_scnnterro',
        ),
    ]
