# Generated by Django 3.1.7 on 2021-04-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210403_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='char2_scnnterro',
            new_name='char2_scndinterro',
        ),
    ]
