# Generated by Django 3.1.7 on 2021-04-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210403_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_members',
            field=models.JSONField(default=None, null=True),
        ),
    ]
